//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailContext.MailContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherConfiguration
    {
        public long Id { get; set; }
        public Nullable<int> StartNo { get; set; }
        public Nullable<int> EndNo { get; set; }
        public Nullable<int> BodyLength { get; set; }
        public Nullable<int> CurrentNo { get; set; }
    }
}
