//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailContext.MailContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherNumbering
    {
        public long ID { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Style { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> BodyLength { get; set; }
        public Nullable<int> TotalLength { get; set; }
        public Nullable<int> StartNo { get; set; }
        public Nullable<int> EndNo { get; set; }
        public Nullable<int> CurrentNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> IsPrefillzero { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
